########################
# Author: Mengjuei Hsieh

language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - graphviz
cache:
  directories:
    - $HOME/.ccache

install:
  - echo CC         = gcc-4.8 > settings.mk
  - echo CXX        = g++-4.8 >> settings.mk
  - echo FC         = gfortran-4.8 >> settings.mk
  - echo CCACHE_DIR = $HOME/.ccache >> settings.mk
  - make -j blasr
  #- make -j CC=gcc-4.8 CXX=g++-4.8 FC=gfortran-4.8 CCACHE_DIR=$HOME/.ccache GenomicConsensus ConsensusCore2
  #- cat /proc/cpuinfo
  #- make -j2 CC=gcc-4.8 CXX=g++-4.8 FC=gfortran-4.8 CCACHE_DIR=$HOME/.ccache pbfalcon

script:
  - echo "success!"
