########################
# Author: Mengjuei Hsieh

language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - graphviz
      - python-dev
      - pep8
      - cmake-data
      - cmake
      - oracle-java8-installer
#     - oracle-java8-set-default
cache:
  directories:
    - $HOME/.ccache
    - $HOME/.ivy2
    - $HOME/.ivy
    - $HOME/distfiles
    - $HOME/local.pip

#before_install:
#    - dpkg-query -L oracle-java8-installer
install:
    - ls -l /usr/lib/jvm/java-8-oracle/jre/bin/java
#    - bin/travisbuild.sh

#script:
#    - /bin/ls $HOME/local/bin
#    - bin/travistest.sh
