########################
# Author: Mengjuei Hsieh

language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - graphviz
      - python-dev
      - cmake-data
      - cmake
cache:
  directories:
    - $HOME/.ccache
    - $HOME/distfiles

install:
  - bin/travisbuild.sh

script:
  - bin/travistest.sh
