########################
# Author: Mengjuei Hsieh

language: cpp

sudo: false

addons:
  apt:
    packages:
      - gfortran
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
#      - autoreconf
#      - automake
#      - libtool

install:
  - echo "success!"
#  - make blasr

script:
  - echo "success!"

#notifications:
#  email:
#    recipients:
#      - mhsieh@pacificbiosciences.com
#
#  irc:
#    channels:
#      - "irc.freenode.org#osxchat"
#    use_notice: true
#    on_success: change
