########################
# Author: Mengjuei Hsieh

language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
cache:
  directories:
    - $HOME/.ccache

install:
  - make CC=gcc-4.8 CXX=g++-4.8 FC=gfortran-4.8 CCACHE_DIR=$HOME/.ccache -j blasr

script:
  - echo "success!"
