########################
# Author: Mengjuei Hsieh

language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - graphviz
      - python-dev
      - pep8
      - cmake-data
      - cmake
      - oracle-java8-installer
cache:
  directories:
    - $HOME/.ccache
    - $HOME/.ivy2
    - $HOME/.ivy
    - $HOME/distfiles
    - $HOME/local.pip

install:
    - dpkg --list|grep -i jav
    - java -version
    - which java
#build:
#    - bin/travisbuild.sh

#script:
#    - /bin/ls $HOME/local/bin
#    - bin/travistest.sh
