########################
# Author: Mengjuei Hsieh

language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
      - boost-latest
    packages:
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - graphviz
      - python-dev
      - cmake-data
      - cmake
      - libboost1.55-all-dev
cache:
  directories:
    - $HOME/.ccache

install:
  - cp mk/travis.mk settings.mk
  - make -j blasr

script:
  - echo "success!"
