########################
# Author: Mengjuei Hsieh

language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8

install:
  - make CC=gcc-4.8 CXX=g++-4.8 FC=gfortran-4.8 blasr

script:
  - echo "success!"

#notifications:
#  email:
#    recipients:
#      - mhsieh@pacificbiosciences.com
#
#  irc:
#    channels:
#      - "irc.freenode.org#osxchat"
#    use_notice: true
#    on_success: change
