########################
# Author: Mengjuei Hsieh

language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - graphviz
      - python-dev
      - cmake-data
      - cmake
cache:
  directories:
    - $HOME/.ccache

install:
  - echo CC          = gcc-4.8 > settings.mk
  - echo CXX         = g++-4.8 >> settings.mk
  - echo FC          = gfortran-4.8 >> settings.mk
  - echo CCACHE_DIR  = $HOME/.ccache >> settings.mk
  - echo HAVE_PYTHON = >> settings.mk
  - echo HAVE_CMAKE  = >> settings.mk
  - make -j blasr

script:
  - echo "success!"
