########################
# Author: Mengjuei Hsieh

language: c

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9
      - graphviz
      - python-dev
      - pep8
      - cmake-data
      - cmake
      - libopenblas-dev
#      - oracle-java8-installer

before_install:
    - mkdir -p $HOME/distfiles

install:
    - bin/travisbuild.sh

script:
    - ls $HOME/local/bin
    - bin/travistest.sh

cache:
  directories:
    - $HOME/.ccache
    - $HOME/.ivy2/cache
    - $HOME/.pip
    - $HOME/distfiles

before_cache:
    - find $HOME/.pip/wheels -type f ! -name '*none-any.whl' -print -delete
#     - find $HOME/.ivy2 -name "ivydata-*.properties" -delete -print
